server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aurora?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    # druid配置, 详细配置项参考 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      # druid 数据源配置, 继承spring.datasource.* 配置, 相同则覆盖
      initialSize: 2
      max-active: 20
      max-wait: 60000
      min-idle: 1
      # 配置下面参数用于启动监控页面, 考虑安全问题, 默认是关闭的, 按需开启
  #      stat-view-servlet:
  #        enabled: true
  #        login-password: abc.123
  #        login-username: druid
  #      filter:
  #        stat:
  #          enabled: true
  #      web-stat-filter:
  #        enabled: true
  # jpa配置
#  jpa:
#    database: MYSQL
#    show-sql: true
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext


mybatis:
  # 指定xml文件位置
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 驼峰命名转换
    map-underscore-to-camel-case: true

logging:
  level:
    pers.wk.ayanami: DEBUG
